# function = allows you to partition code into smaller, reusable pieces (with names).
def girls():
# What girls might like
        print("Girls may like feeling appreciated and respected.")
        print("Girls often enjoy meaningful conversations.")
        print("Girls can like spending time with close friends.")
        print("Girls may enjoy thoughtful surprises.")
        print("Girls often appreciate honesty and trust.")
        print("Girls may like expressing themselves creatively.")
        print("Girls can enjoy music, movies, and entertainment.")
        print("Girls may like feeling understood and listened to.")
        print("Girls often enjoy laughter and fun moments.")
        print("Girls may like achieving their personal goals.")
        print("Girls can enjoy fashion and personal style.")
        print("Girls may like traveling and exploring new places.")
        print("Girls often appreciate kindness and empathy.")
        print("Girls may enjoy hobbies like reading or art.")
        print("Girls can like building strong relationships.")
        print("Girls may enjoy feeling safe and supported.")
        print("Girls often like positive and uplifting energy.")
        print("Girls may enjoy learning new things.")
        print("Girls can like celebrating special occasions.")
        print("Girls may appreciate people who are genuine.")

# What boys might like
def boys():
        print("Boys may like competition and challenges.")
        print("Boys often enjoy sports and physical activities.")
        print("Boys can like video games and technology.")
        print("Boys may enjoy spending time with friends.")
        print("Boys often appreciate humor and jokes.")
        print("Boys may like achieving goals and winning.")
        print("Boys can enjoy adventure and excitement.")
        print("Boys may like building or creating things.")
        print("Boys often enjoy music and entertainment.")
        print("Boys may like independence and freedom.")
        print("Boys can enjoy learning new skills.")
        print("Boys may like cars, gadgets, or tools.")
        print("Boys often appreciate loyalty and respect.")
        print("Boys may enjoy teamwork and group activities.")
        print("Boys can like exploring new ideas.")
        print("Boys may enjoy relaxing and having fun.")
        print("Boys often like being recognized for efforts.")
        print("Boys may enjoy solving problems.")
        print("Boys can like trying new experiences.")
        print("Boys may appreciate honesty and trust.")


girls()        
